services:
  fake-data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fake_data_script
    volumes:
      - .:/app
    env_file:
      - ../../service_env.env
    networks:
      - source-net
networks:
  source-net:
    external: true
