CREATE database dwh;
\c dwh
------ staging metadata ------------
CREATE SCHEMA IF NOT EXISTS staging_metadata;

CREATE TABLE IF NOT EXISTS staging_metadata.snapshot_tracker (
  lake_table_name VARCHAR(255) PRIMARY KEY,
  last_snapshot_id BIGINT,
  last_load_time TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staging_metadata.load_tracker (
  lake_table_name VARCHAR(255),
  load_id BIGINT,
  load_time TIMESTAMP,
  status VARCHAR(50),
  records_loaded BIGINT,
  error_message TEXT
);

--- staging -------
CREATE SCHEMA IF NOT EXISTS staging;
CREATE TABLE IF NOT EXISTS staging.ct_address (
    nb_dot_dieu_tri_id INT,
    so_nha TEXT,
    xa_phuong_id INT,
    xa_phuong_tam_tru_id INT,
    quan_huyen_id INT,
    quan_huyen_tam_tru_id INT,
    tinh_thanh_pho_id INT,
    tinh_thanh_pho_tam_tru_id INT,
    dia_chi_cong_ty TEXT,
    ten_cong_ty TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.ct_bo_chi_dinh (
    id INT,
    nb_dot_dieu_tri_id INT,
    bo_chi_dinh_id INT,
    thoi_gian_chi_dinh TIMESTAMP,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.ct_dich_vu (
    id INT,
    nb_dot_dieu_tri_id INT,
    bac_si_chi_dinh_id INT,
    chi_dinh_tu_dich_vu_id INT,
    chi_dinh_tu_loai_dich_vu INT,
    dich_vu_id INT,
    doi_tuong_kcb INT,
    dung_tuyen INT,
    ghi_chu TEXT,
    gia_bao_hiem INT,
    gia_goc TEXT,
    gia_khong_bao_hiem INT,
    gia_phu_thu INT,
    khoa_chi_dinh_id INT,
    khong_thu_tien BOOLEAN,
    khong_tinh_tien BOOLEAN,
    loai_dich_vu INT,
    loai_doi_tuong_id INT,
    loai_hinh_thanh_toan_id TEXT,
    mien_cung_chi_tra BOOLEAN,
    muc_huong TEXT,
    nb_bo_chi_dinh_id INT,
    nb_chuyen_khoa_id TEXT,
    nb_goi_dv_chi_tiet_id TEXT,
    nb_goi_pt_tt_id TEXT,
    nb_the_bao_hiem_id TEXT,
    ngoai_vien BOOLEAN,
    phan_tram_mien_giam_dich_vu_bh FLOAT,
    phan_tram_mien_giam_dich_vu_khong_bh FLOAT,
    phat_hanh_hoa_don BOOLEAN,
    phieu_doi_tra_id TEXT,
    phieu_thu_id INT,
    so_luong INT,
    stt_hien_thi TEXT,
    thanh_toan INT,
    thoi_gian_chi_dinh TIMESTAMP,
    thoi_gian_thuc_hien TIMESTAMP,
    tien_bh_thanh_toan INT,
    tien_giam_gia_bh INT,
    tien_giam_gia_khong_bh INT,
    tien_mien_giam_dich_vu_bh INT,
    tien_mien_giam_dich_vu_khong_bh INT,
    tien_mien_giam_dich_vu_nhap_vao INT,
    tien_mien_giam_phieu_thu_bh INT,
    tien_mien_giam_phieu_thu_khong_bh INT,
    tien_nb_cung_chi_tra INT,
    tien_nb_phu_thu INT,
    tien_nb_trai_tuyen INT,
    tien_nb_tu_tra INT,
    tien_nguon_khac INT,
    trang_thai_hoan INT,
    tu_tra BOOLEAN,
    ty_le_bh_tt INT,
    ty_le_tt_dv INT,
    dv_gia_id TEXT,
    nb_phac_do_dieu_tri_id TEXT,
    phac_do_dieu_tri_dich_vu_id TEXT,
    ngoai_vien_id TEXT,
    nguon_khac_id TEXT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.ct_dot_dieu_tri (
    id INT,
    cap_cuu BOOLEAN,
    chi_nam_sinh BOOLEAN,
    dan_toc_id INT,
    doi_tuong INT,
    doi_tuong_kcb INT,
    email TEXT,
    gioi_tinh INT,
    kham_suc_khoe BOOLEAN,
    khoa_id INT,
    khoa_tiep_don_id INT,
    loai_benh_an_id INT,
    loai_doi_tuong_id INT,
    ma_benh_an TEXT,
    ma_ho_so INT,
    ma_nb INT,
    mac_dinh BOOLEAN,
    nb_thong_tin_id INT,
    ngay_sinh TIMESTAMP,
    nghe_nghiep_id TEXT,
    ngoai_vien BOOLEAN,
    nguoi_lap_benh_an_id INT,
    nhom_mau TEXT,
    noi_lam_viec TEXT,
    phan_loai_nb_id INT,
    quoc_tich_id INT,
    so_bao_hiem_xa_hoi TEXT,
    so_dien_thoai TEXT,
    so_ngay_dieu_tri INT,
    so_phoi TEXT,
    ten_nb TEXT,
    ten_nb_khong_dau TEXT,
    thoi_gian_lap_benh_an TIMESTAMP,
    thoi_gian_ra_vien TIMESTAMP,
    thoi_gian_vao_vien TIMESTAMP,
    tiem_chung BOOLEAN,
    trang_thai INT,
    uu_tien BOOLEAN,
    duyet_chi_phi TEXT,
    bang_lai_xe_id TEXT,
    ma_doi_tuong_kcb_id TEXT,
    nhan_vien_kinh_doanh_id TEXT,
    can_nang_vao_vien TEXT,
    cong_ty_bao_hiem_id TEXT,
    phan_loai_doi_tuong INT,
    nguoi_duyet_chi_phi_id TEXT,
    nguoi_gui_duyet_chi_phi_id TEXT,
    nguoi_tu_choi_duyet_chi_phi_id TEXT,
    loai_lien_ket TEXT,
    nb_lien_ket_id TEXT,
    ho_ngheo BOOLEAN,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.ct_phieu_thu (
    id INT,
    active BOOLEAN,
    deleted INT,
    nb_dot_dieu_tri_id INT,
    ca_lam_viec_id INT,
    doi_tuong_kcb INT,
    ds_ma_giam_gia_id TEXT,
    ghi_chu TEXT,
    hinh_thuc_mien_giam INT,
    hoa_don_id TEXT,
    ky_hieu TEXT,
    loai_phieu_thu INT,
    nb_goi_dv_id TEXT,
    nha_thu_ngan_id INT,
    nho_hon_muc_cung_chi_tra BOOLEAN,
    phan_tram_mien_giam FLOAT,
    quay_id INT,
    so_phieu INT,
    thanh_tien INT,
    thanh_toan INT,
    thoi_gian_huy_thanh_toan TIMESTAMP,
    thoi_gian_thanh_toan TIMESTAMP,
    thu_ngan_huy_thanh_toan_id INT,
    thu_ngan_id INT,
    tien_bh_thanh_toan INT,
    tien_bh_thanh_toan_trong_goi INT,
    tien_giam_gia INT,
    tien_hoan_tra INT,
    tien_mien_giam_dich_vu INT,
    tien_mien_giam_phieu_thu INT,
    tien_mien_giam_phieu_thu_nhap_vao INT,
    tien_nb_cung_chi_tra INT,
    tien_nb_cung_chi_tra_trong_goi INT,
    tien_nb_phu_thu INT,
    tien_nb_tu_tra INT,
    tien_nguon_khac INT,
    tien_tai_tro_bao_hiem INT,
    tien_tai_tro_khong_bao_hiem INT,
    trang_thai_hoa_don INT,
    hoan_ung BOOLEAN,
    loai_mien_giam TEXT,
    phieu_doi_tra_id TEXT,
    thoi_gian_tao_phieu TIMESTAMP,
    thoi_gian_cap_nhat_phieu TIMESTAMP,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.ct_dv_kham (
    id INT,
    nb_dot_dieu_tri_id INT,
    bac_si_ket_luan_id INT,
    bac_si_kham_id INT,
    dot_kham_moi BOOLEAN,
    nguoi_phien_dich_id TEXT,
    stt_chuyen_khoa TEXT,
    thiet_lap TEXT,
    thoi_gian_kham TIMESTAMP,
    thoi_gian_ket_luan TIMESTAMP,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.ct_dv_kham_ket_luan (
    id INT,
    nb_bo_chi_dinh_id INT,
    huong_dieu_tri INT,
    ket_qua_dieu_tri INT,
    loi_dan TEXT,
    phong_hen_kham_id INT,
    so_ngay_cho_don INT,
    thoi_gian_hen_tai_kham TIMESTAMP,
    thoi_gian_ket_luan TIMESTAMP,
    so_hen_kham TEXT,
    thong_tin_theo_doi TEXT,
    den_ngay TIMESTAMP,
    tu_ngay TIMESTAMP,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.ct_dv_ky_thuat (
    id INT,
    cap_cuu BOOLEAN,
    hinh_thuc_tt_ksk INT,
    in_phieu_chi_dinh INT,
    nb_dot_dieu_tri_id INT,
    ngoai_vien_id TEXT,
    phieu_in_id INT,
    phong_thuc_hien_id INT,
    so_lan_goi INT,
    so_phieu_id INT,
    stt INT,
    tam_ung BOOLEAN,
    thanh_toan_sau BOOLEAN,
    theo_yeu_cau BOOLEAN,
    thoi_gian_lay_so TIMESTAMP,
    thoi_gian_tiep_nhan TIMESTAMP,
    thuc_hien_tai_khoa BOOLEAN,
    trang_thai INT,
    tu_van_vien_id TEXT,
    uu_tien BOOLEAN,
    ly_do_khong_thuc_hien TEXT,
    thoi_gian_xac_nhan_khong_thuc_hien TIMESTAMP,
    khong_thuc_hien BOOLEAN,
    ly_doi_khong_thuc_hien TEXT,  
    trang_thai_thong_bao TEXT,
    thoi_gian_bat_dau TIMESTAMP,
    thoi_gian_hoan_thanh TIMESTAMP,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.ct_kham_suc_khoe (
    id INT,
    chuc_vu TEXT,
    den_thoi_gian_kham TEXT,
    den_thoi_gian_lay_mau TEXT,
    dia_diem_kham TEXT,
    dia_diem_lay_mau TEXT,
    ds_bo_chi_dinh_id TEXT,
    ds_dich_vu_id TEXT,
    hinh_thuc_tt_dv_ngoai_hd INT,
    hop_dong_ksk_id INT,
    ma_nhan_vien TEXT,
    ngoai_vien BOOLEAN,
    phong_ban TEXT,
    stt INT,
    thoi_gian_hoan_thanh TEXT,
    trang_thai INT,
    tu_thoi_gian_kham TEXT,
    tu_thoi_gian_lay_mau TEXT,
    hinh_thuc_tt_dv_trong_hd INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.ct_nguon_nb (
    nb_dot_dieu_tri_id INT,
    ghi_chu TEXT,
    nguoi_gioi_thieu_id INT,
    nguon_nb_id INT,  
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.hospital_configs (
    id INT,
    table_name TEXT,
    name TEXT,
    value_code TEXT,
    description TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

----------- Dm--------
CREATE TABLE IF NOT EXISTS staging.dm_benh_nhan (
    nb_thong_tin_id INT,
    ma_nb BIGINT,
    email TEXT,
    ngay_sinh TIMESTAMP,
    noi_lam_viec TEXT,
    so_dien_thoai TEXT,
    ten_nb TEXT,
    ten_nb_khong_dau TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_bo_chi_dinh (
    id INT,
    code_bo_chi_dinh TEXT,
    ten TEXT,
    ds_bac_si_chi_dinh_id TEXT,
    ds_doi_tuong_su_dung TEXT,
    ds_kho_id TEXT,
    ds_loai_dich_vu TEXT,
    han_che_khoa_chi_dinh BOOLEAN,
    hop_dong_ksk_id FLOAT,
    thuoc_chi_dinh_ngoai BOOLEAN,
    ket_qua_lau BOOLEAN,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_chuyen_khoa (
    id INT,
    ten TEXT,
    code_chuyen_khoa TEXT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_dich_vu (
    id INT,
    code_dichvu TEXT,
    ten TEXT,
    don_vi_tinh_id INT,
    ds_nguon_khac_chi_tra TEXT,
    gia_bao_hiem TEXT,
    gia_khong_bao_hiem INT,
    khong_tinh_tien INT,
    loai_dich_vu INT,
    nhom_dich_vu_cap1_id INT,
    nhom_dich_vu_cap2_id INT,
    nhom_dich_vu_cap3_id INT,
    ten_tuong_duong TEXT,
    thu_ngoai BOOLEAN,
    ty_le_bh_tt INT,
    ty_le_tt_dv INT,
    viet_tat TEXT,
    chi_dinh_sl_le BOOLEAN,
    nguon_khac_id TEXT,
    gui_vitimes BOOLEAN,
    mien_phi_giam_doc_duyet BOOLEAN,
    khong_su_dung BOOLEAN,
    online_ BOOLEAN,
    sua_gia BOOLEAN,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_doi_tuong_kcb (
    id INT,
    ten TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_dv_discount (
    id INT,
    discount_percent FLOAT,
    loai_dich_vu_id TEXT,
    type_discount INT,
    fix_amount BIGINT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_hoc_ham_hoc_vi (
    id INT,
    code_hoc_ham TEXT,
    ten TEXT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_hop_dong_ksk (
    id INT,
    code_hop_dong INT,
    ten TEXT,
    ds_ma_giam_gia_id TEXT,
    hinh_thuc_mien_giam FLOAT,
    hinh_thuc_tt_dv_ngoai_hd INT,
    ngay_hieu_luc TEXT,
    phan_tram_mien_giam FLOAT,
    so_hop_dong TEXT,
    thoi_gian_thanh_ly TEXT,
    tien_chua_thanh_toan INT,
    tien_da_thanh_toan INT,
    tien_du_kien INT,
    tien_du_kien_sau_giam INT,
    tien_giam_gia INT,
    tien_mien_giam_dich_vu INT,
    tien_mien_giam_hop_dong INT,
    tien_thuc_te INT,
    tien_thuc_te_sau_giam INT,
    trang_thai INT,
    chot_thanh_toan_dv_ksk INT,
    tien_nb_da_thanh_toan INT,
    tien_tai_tro_nb INT,
    nguoi_gioi_thieu_id INT,
    nguon_nb_id INT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_khoa (
    id INT,
    code_khoa TEXT,
    ten TEXT,
    ds_tinh_chat_khoa TEXT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_loai_dich_vu (
    id INT,
    ten TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_nguoi_gioi_thieu (
    id INT,
    code_nguoi_gioi_thieu TEXT,
    ten TEXT,
    ds_nguon_nb_id TEXT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_nguon_nb (
    id INT,
    code_nguon_nb TEXT,
    ten TEXT,
    nguoi_gioi_thieu BOOLEAN,
    nhom_nguon INT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_nhan_vien (
    id INT,
    code_nhan_vien TEXT,
    ten TEXT,
    chung_chi TEXT,
    ds_chuyen_khoa_id TEXT,
    email TEXT,
    gioi_tinh TEXT,
    hoc_ham_hoc_vi_id INT,
    ngay_sinh TIMESTAMP,
    van_bang_id INT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_nhom_dich_vu_cap1 (
    id INT,
    code_service_lvl_1 TEXT,
    ten TEXT,
    loai_dich_vu FLOAT,
    stt_bang_ke INT,
    trang_thai_hoan_thanh INT,
    trang_thai_lay_stt INT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_nhom_dich_vu_cap2 (
    id INT,
    code_service_lvl_2 TEXT,
    ten TEXT,
    luu_phim_chup BOOLEAN,
    nhom_dich_vu_cap1_id INT,
    phieu_chi_dinh_id INT,
    tach_stt_noi_tru BOOLEAN,
    tach_stt_uu_tien BOOLEAN,
    theo_yeu_cau BOOLEAN,
    tiep_don_cls BOOLEAN,
    trang_thai_hoan_thanh INT,
    trang_thai_lay_stt INT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_nhom_dich_vu_cap3 (
    id INT,
    code_service_lvl_3 TEXT,
    ten TEXT,
    nhom_dich_vu_cap2_id INT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_phong (
    id INT,
    code_phong TEXT,
    ten TEXT,
    chuyen_khoa_id INT,
    dia_diem TEXT,
    ds_loai_phong TEXT,
    khoa_id INT,
    ngoai_tru BOOLEAN,
    ngoai_vien BOOLEAN,
    noi_tru BOOLEAN,
    online BOOLEAN,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_quan_huyen (
    id INT,
    ten TEXT,
    code_quan_huyen INT,
    ma_tcqg INT,
    tinh_thanh_pho_id INT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_tinh_thanh_pho (
    id INT,
    code_province INT,
    ten TEXT,
    ma_tcqg INT,
    active BOOLEAN,
    deleted INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS staging.dm_xa_phuong (
    xa_phuong_id INT,
    ten_xa_phuong TEXT,
    quan_huyen_id INT,
    partition_col TEXT,
    op TEXT,
    is_deleted BOOLEAN
);
