version: 2

sources:
  - name: staging
    schema: staging
    tables:
      - name: dm_benh_nhan
      - name: dm_nhan_vien
      - name: dm_dich_vu
      - name: ct_dot_dieu_tri
      - name: ct_dv_kham
      - name: ct_dv_kham_ket_luan
