version: 2

sources:
  - name: staging
    database: "{{ env_var('WAREHOUSE_POSTGRES_DB') }}"
    schema: staging
    tables:
      - name: dm_benh_nhan
      - name: dm_dich_vu
      - name: ct_dot_dieu_tri
      - name: dm_khoa
      - name: dm_nhan_vien
      - name: dm_phong
      - name: ct_dv_kham
      - name: ct_dich_vu
      - name: dm_bo_chi_dinh
      - name: ct_phieu_thu
      - name: ct_bo_chi_dinh
      - name: ct_dv_kham_ket_luan
      - name: ct_dv_ky_thuat
      - name: ct_kham_suc_khoe
      - name: ct_nguon_nb
      - name: dm_nhom_dich_vu_cap1
      - name: dm_nhom_dich_vu_cap2
      - name: dm_nhom_dich_vu_cap3
      - name: dm_hop_dong_ksk
      - name: dm_dv_discount
      - name: dm_tinh_thanh_pho
      - name: dm_quan_huyen
      - name: dm_xa_phuong
      - name: dm_chuyen_khoa
      - name: dm_doi_tuong_kcb
      - name: dm_hoc_ham_hoc_vi
      - name: dm_loai_dich_vu
      - name: dm_nguoi_gioi_thieu
      - name: ct_address
      - name: hospital_configs
      - name: dm_nguon_nb
