spark.eventLog.enabled           true
spark.eventLog.dir               file:///tmp/spark-events
spark.history.fs.logDirectory    file:///tmp/spark-events
spark.sql.shuffle.partitions     200
spark.master                     spark://spark-es-master:7077