services:
  # --- Superset App ---
  superset:
    image: ${BI_SUPERSET_IMAGE}
    container_name: superset_bi
    user: "root"
    restart: unless-stopped
    ports:
      - "${BI_SUPERSET_PORT}:8088"
    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      PYTHONPATH: /app/pythonpath
      BI_SUPERSET_USER: ${BI_SUPERSET_USER}
      BI_SUPERSET_PASS: ${BI_SUPERSET_PASS}
    volumes:
      - ./superset_data:/app/superset_home
      - ../superset_config.py:/app/pythonpath/superset_config.py
      - ./superset-init.sh:/app/superset-init.sh
    command: ["/bin/bash", "/app/superset-init.sh"]
    networks:
      - warehouse-net

networks:
  warehouse-net:
    external: true

volumes:
  superset_data:
