services:
  # Hive Metastore Service
  hive-metastore:
    image: ${LAKE_HIVE_METASTORE_IMAGE}
    container_name: lake_hive_metastore
    env_file:
      - ../../../.env
    environment:
      SERVICE_NAME: metastore
      # Config Metastore Database
      HIVE_SITE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://postgres-hive:5432/${POSTGRES_DB}"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName: "org.postgresql.Driver"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName: "${POSTGRES_USER}"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword: "${POSTGRES_PASSWORD}"
      # Config Warehouse (MinIO)
      HIVE_SITE_CONF_hive_metastore_warehouse_dir: "${LAKE_HIVE_WAREHOUSE_DIR}"
      HIVE_SITE_CONF_fs_s3a_access_key: "${LAKE_MINIO_ROOT_USER}"
      HIVE_SITE_CONF_fs_s3a_secret_key: "${LAKE_MINIO_ROOT_PASSWORD}"
      HIVE_SITE_CONF_fs_s3a_endpoint: "${LAKE_MINIO_ENDPOINT}"
      HIVE_SITE_CONF_fs_s3a_path_style_access: "true"
      HIVE_SITE_CONF_fs_s3a_impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    ports:
      - "${HIVE_METASTORE_PORT:-9083}:9083"
    # Mount driver PostgreSQL 
    volumes:
      - ../jars/postgresql-42.7.9.jar:/opt/hive/lib/postgresql-42.7.9.jar
      - ../jars/hadoop-aws-3.1.3.jar:/opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.1.3.jar
      - ../jars/aws-java-sdk-bundle-1.11.375.jar:/opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.375.jar
      
    entrypoint: >
      /bin/sh -c "
      /opt/hive/bin/schematool -dbType postgres -info -url 'jdbc:postgresql://postgres-hive:5432/${POSTGRES_DB}' -driver 'org.postgresql.Driver' -userName '${POSTGRES_USER}' -passWord '${POSTGRES_PASSWORD}' || \
      /opt/hive/bin/schematool -dbType postgres -initSchema -url 'jdbc:postgresql://postgres-hive:5432/${POSTGRES_DB}' -driver 'org.postgresql.Driver' -userName '${POSTGRES_USER}' -passWord '${POSTGRES_PASSWORD}';
      /entrypoint.sh metastore
      "

    networks:
      - lake_net

networks:
  lake_net:
    external: true