hospital_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-warehouse
      user: "{{ env_var('WAREHOUSE_POSTGRES_USER') }}"
      pass: "{{ env_var('WAREHOUSE_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('WAREHOUSE_POSTGRES_DB') }}"
      schema: public
      threads: 4
