version: '3.8'

services:
  # =========================================
  # 4. Flink (Job Manager & Task Manager)
  # =========================================
  flink-jobmanager:
    image: ${LAKE_FLINK_IMAGE}
    container_name: flink_jobmanager
    command: jobmanager
    env_file:
      - ../../../.env
    ports:
      - "${LAKE_FLINK_JOBMANAGER_PORT}:8081"
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - lake_net

  flink-taskmanager:
    image: ${LAKE_FLINK_IMAGE}
    container_name: flink_taskmanager
    command: taskmanager
    env_file:
      - ../../../.env
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
    depends_on:
      - flink-jobmanager
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - lake_net

networks:
  lake_net:
    external: true
