services:
  flink-jobmanager:
    image: ${LAKE_FLINK_IMAGE}
    container_name: flink_jobmanager
    command: jobmanager
    env_file:
      - ../../../.env
    volumes:
      # Config
      - ./core-site.xml:/opt/flink/conf/core-site.xml
      - ./hive-site.xml:/opt/flink/conf/hive-site.xml



      # Connectors - Kafka
      - ../jars/flink-connector-kafka-3.1.0-1.18.jar:/opt/flink/lib/flink-connector-kafka-3.1.0-1.18.jar
      - ../jars/kafka-clients-3.7.0.jar:/opt/flink/lib/kafka-clients-3.7.0.jar
      # Connectors - jdbc
      - ../jars/flink-connector-jdbc-3.1.2-1.18.jar:/opt/flink/lib/flink-connector-jdbc-3.1.2-1.18.jar
      # Connectors - hive
      - ../jars/flink-sql-connector-hive-3.1.3_2.12-1.18.1.jar:/opt/flink/lib/flink-sql-connector-hive-3.1.3_2.12-1.18.1.jar

      # Iceberg
      - ../jars/iceberg-flink-runtime-1.18-1.6.1.jar:/opt/flink/lib/iceberg-flink-runtime-1.18-1.6.1.jar
      - ../jars/iceberg-aws-bundle-1.6.1.jar:/opt/flink/lib/iceberg-aws-bundle-1.6.1.jar

      # Hive
      - ../jars/hive-exec-3.1.3.jar:/opt/flink/lib/hive-exec-3.1.3.jar
      - ../jars/libfb303-0.9.3.jar:/opt/flink/lib/libfb303-0.9.3.jar


      # JDBC
      - ../jars/postgresql-42.7.9.jar:/opt/flink/lib/postgresql-42.7.9.jar

      # S3 / MinIO
      - ../jars/aws-java-sdk-bundle-1.12.785.jar:/opt/flink/lib/aws-java-sdk-bundle-1.12.785.jar
      # Hadoop
      - ../jars/hadoop-common-3.3.6.jar:/opt/flink/lib/hadoop-common-3.3.6.jar
      - ../jars/hadoop-auth-3.3.6.jar:/opt/flink/lib/hadoop-auth-3.3.6.jar
      - ../jars/hadoop-aws-3.3.6.jar:/opt/flink/lib/hadoop-aws-3.3.6.jar
      - ../jars/hadoop-hdfs-3.3.6.jar:/opt/flink/lib/hadoop-hdfs-3.3.6.jar
      - ../jars/hadoop-hdfs-client-3.3.6.jar:/opt/flink/lib/hadoop-hdfs-client-3.3.6.jar
      - ../jars/woodstox-core-5.0.3.jar:/opt/flink/lib/woodstox-core-5.0.3.jar
      - ../jars/stax2-api-4.2.1.jar:/opt/flink/lib/stax2-api-4.2.1.jar
      - ../jars/commons-configuration2-2.8.0.jar:/opt/flink/lib/commons-configuration2-2.8.0.jar
      - ../jars/hadoop-shaded-guava-1.1.1.jar:/opt/flink/lib/hadoop-shaded-guava-1.1.1.jar
      - ../jars/commons-logging-1.2.jar:/opt/flink/lib/commons-logging-1.2.jar
      - ../jars/hadoop-mapreduce-client-core-3.3.6.jar:/opt/flink/lib/hadoop-mapreduce-client-core-3.3.6.jar
    
      # Job
      - ./flink-sql-job/target/flink-sql-job-1.0.jar:/opt/flink/jobs/flink-sql-job-1.0.jar
    ports:
      - "127.0.0.1:${LAKE_FLINK_JOBMANAGER_PORT}:8081"
    environment:
      AWS_REGION: ${LAKE_FLINK_AWS_REGION}
      HIVE_CONF_DIR: /opt/flink/conf
      HADOOP_CONF_DIR: /opt/flink/conf
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager

    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - lake-net
      - source-net

  flink-taskmanager:
    image: ${LAKE_FLINK_IMAGE}
    container_name: flink_taskmanager
    command: taskmanager
    env_file:
      - ../../../.env
    volumes:
      # Config
      - ./core-site.xml:/opt/flink/conf/core-site.xml
      - ./hive-site.xml:/opt/flink/conf/hive-site.xml

      # Connectors - Kafka
      - ../jars/flink-connector-kafka-3.1.0-1.18.jar:/opt/flink/lib/flink-connector-kafka-3.1.0-1.18.jar
      - ../jars/kafka-clients-3.7.0.jar:/opt/flink/lib/kafka-clients-3.7.0.jar
      # Connectors - jdbc
      - ../jars/flink-connector-jdbc-3.1.2-1.18.jar:/opt/flink/lib/flink-connector-jdbc-3.1.2-1.18.jar
      # Connectors - hive
      - ../jars/flink-sql-connector-hive-3.1.3_2.12-1.18.1.jar:/opt/flink/lib/flink-sql-connector-hive-3.1.3_2.12-1.18.1.jar

      # Iceberg
      - ../jars/iceberg-flink-runtime-1.18-1.6.1.jar:/opt/flink/lib/iceberg-flink-runtime-1.18-1.6.1.jar
      - ../jars/iceberg-aws-bundle-1.6.1.jar:/opt/flink/lib/iceberg-aws-bundle-1.6.1.jar
      # Hive
      - ../jars/hive-exec-3.1.3.jar:/opt/flink/lib/hive-exec-3.1.3.jar
      - ../jars/libfb303-0.9.3.jar:/opt/flink/lib/libfb303-0.9.3.jar

      # JDBC
      - ../jars/postgresql-42.7.9.jar:/opt/flink/lib/postgresql-42.7.9.jar

      # S3 / MinIO
      - ../jars/aws-java-sdk-bundle-1.12.785.jar:/opt/flink/lib/aws-java-sdk-bundle-1.12.785.jar
      # Hadoop
      - ../jars/hadoop-common-3.3.6.jar:/opt/flink/lib/hadoop-common-3.3.6.jar
      - ../jars/hadoop-auth-3.3.6.jar:/opt/flink/lib/hadoop-auth-3.3.6.jar
      - ../jars/hadoop-aws-3.3.6.jar:/opt/flink/lib/hadoop-aws-3.3.6.jar
      - ../jars/hadoop-hdfs-3.3.6.jar:/opt/flink/lib/hadoop-hdfs-3.3.6.jar
      - ../jars/hadoop-hdfs-client-3.3.6.jar:/opt/flink/lib/hadoop-hdfs-client-3.3.6.jar
      - ../jars/woodstox-core-5.0.3.jar:/opt/flink/lib/woodstox-core-5.0.3.jar
      - ../jars/stax2-api-4.2.1.jar:/opt/flink/lib/stax2-api-4.2.1.jar
      - ../jars/commons-configuration2-2.8.0.jar:/opt/flink/lib/commons-configuration2-2.8.0.jar
      - ../jars/hadoop-shaded-guava-1.1.1.jar:/opt/flink/lib/hadoop-shaded-guava-1.1.1.jar
      - ../jars/commons-logging-1.2.jar:/opt/flink/lib/commons-logging-1.2.jar
      - ../jars/hadoop-mapreduce-client-core-3.3.6.jar:/opt/flink/lib/hadoop-mapreduce-client-core-3.3.6.jar
    
      # Job
      - ./flink-sql-job/target/flink-sql-job-1.0.jar:/opt/flink/jobs/flink-sql-job-1.0.jar
    ports:
      - "127.0.0.1:${LAKE_FLINK_TASKMANAGER_PORT}:8082"
    environment:
      AWS_REGION: ${LAKE_FLINK_AWS_REGION}
      HIVE_CONF_DIR: /opt/flink/conf
      HADOOP_CONF_DIR: /opt/flink/conf
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2

    depends_on:
      - flink-jobmanager
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - lake-net
      - source-net
networks:
  lake-net:
    external: true
  source-net:
    external: true
