from faker import Faker
import psycopg2

import os
import random
from psycopg2.extras import execute_values
from dotenv import load_dotenv
from datetime import datetime, timezone, timedelta


class FakerGenerator:

    def __init__(self):
        current_dir = os.path.dirname(os.path.abspath(__file__))
        env_path = os.path.join(current_dir, '..', 'service_env.env')

        load_dotenv(dotenv_path=env_path)
        self.fake = Faker('en_US')
        # ARG
        self.RECORDS_PER_MINUTE = int(os.getenv("RECORDS_PER_MINUTE", 100))
        # DB
        self.FAKE_SOURCE_HOST = os.getenv("FAKE_SOURCE_HOST")
        self.FAKE_SOURCE_PORT = os.getenv("FAKE_SOURCE_PORT")
        self.FAKE_SOURCE_DB = os.getenv("FAKE_SOURCE_DB")
        self.FAKE_SOURCE_USER = os.getenv("FAKE_SOURCE_USER")
        self.FAKE_SOURCE_PASS = os.getenv("FAKE_SOURCE_PASS")
        # Default values for FK
        self.dm_bo_chi_dinh_id = 458
        self.dm_benh_nhan_id = [
            73973, 73974, 73975, 73976, 73977, 73978, 73979, 73980, 73981, 73982,
            73983, 73984, 73985, 73986, 73987, 73988, 73989, 73990, 73991, 73992,
            73993, 73994, 73995, 73996, 73997, 73998, 73999, 74000, 74001, 74002,
            74003, 74004, 74005, 74006, 74007, 74008, 74009, 74010, 74011, 74012,
            74013, 74014, 74015, 74016, 74017, 74018, 74019, 74020, 74021, 74022,
            74023, 74024, 74025, 74026, 74027, 74029, 75742, 74030, 74031, 74032,
            74033, 74034, 74035, 74036, 74037, 74038, 74039, 74040, 74041, 74042,
            74043, 74044, 74045, 74046, 74047, 74048, 74049, 74050, 74051, 74052,
            74053, 74054, 74055, 74056, 74057, 74058, 74059, 74060, 74061, 74062,
            74063, 74064, 74065, 74066, 74067, 74068, 74069, 74070, 74071, 74072
        ]
        self.dm_chuyen_khoa_id = [
            5078, 1660, 3284, 1677, 3828, 3829, 3831, 3832, 3837, 1667,
            1703, 2542, 657, 556, 1726, 1733, 1739, 1752, 2502, 3987,
            5064, 5808, 6413, 6554, 6702, 6755, 6760, 6762, 2503, 2548,
            2592, 3059, 3528, 2865, 3169, 3081, 741, 3686, 742, 2586,
            1020, 1005, 4826, 1007, 5803, 1006, 1032, 1489, 1490, 3200,
            3202, 3203, 1491, 1494, 1497, 1500, 149, 2879, 73, 74,
            6412, 1131, 1634, 6204, 1604, 1605, 1606, 1612, 1613, 1614,
            1615, 1621, 3838, 3841, 3842, 3844, 3846, 3848, 3849, 3862,
            3869, 3877, 3878, 3879, 3880, 3882, 3888, 1201, 3893, 3902,
            3903, 3909, 1637, 1610, 1652, 1662, 1669, 1684, 1699, 1701
        ]
        self.ten_nb = f"fake_{self.fake.name()}"
        self.ten_nb_khong_dau = self.ten_nb
        self.dm_khoa_id = 10
        self.loai_benh_an_id = "TEST_BA"
        self.loai_doi_tuong_id = 1
        self.dm_nguon_nb_id = 52
        self.dm_nhom_dich_vu_cap_1 = 3
        self.thoi_gian_vao_vien = self.fake.date_time_between(
            start_date=datetime(2024, 1, 1), end_date=datetime(2025, 12, 31))

    def db_connect(self):
        try:
            conn = psycopg2.connect(
                host=self.FAKE_SOURCE_HOST,
                port=self.FAKE_SOURCE_PORT,
                dbname=self.FAKE_SOURCE_DB,
                user=self.FAKE_SOURCE_USER,
                password=self.FAKE_SOURCE_PASS
            )
            print("✅ Connect Success")
            return conn
        except Exception as e:
            print("❌ Connect Fail:", e)
            return None

    def alter_table(self, conn):
        try:
            cursor = conn.cursor()
            cursor.execute("""
            ALTER TABLE pgsql_source.ct_dot_dieu_tri
            ALTER COLUMN id SET NOT NULL
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            ALTER TABLE pgsql_source.ct_phieu_thu 
            ALTER COLUMN id SET NOT NULL
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            """)
            conn.commit()
            print("✅ Table Altered Successfully")
        except Exception as e:
            print("❌ Table Alter Failed:", e)
        finally:
            cursor.close()

    def generate_fake_data(self):
        conn = self.db_connect()
        if not conn:
            return

        try:
            cursor = conn.cursor()
            records = []

            now = datetime.now(timezone(timedelta(hours=7)))

            for _ in range(self.RECORDS_PER_MINUTE):
                nb_id = random.choice(self.dm_benh_nhan_id)

                record = (
                    # cap_cuu
                    False,
                    # chi_nam_sinh
                    False,
                    # dan_toc_id
                    None,
                    # doi_tuong
                    1,
                    # doi_tuong_kcb
                    1,
                    # email
                    self.fake.email(),                                  # email
                    # gioi_tinh
                    random.choice([1, 2]),
                    # kham_suc_khoe
                    self.fake.boolean(),
                    # khoa_id
                    self.dm_khoa_id,
                    # khoa_tiep_don_id
                    self.dm_khoa_id,
                    # loai_benh_an_id
                    self.loai_benh_an_id,
                    # loai_doi_tuong_id
                    self.loai_doi_tuong_id,
                    # ma_benh_an
                    None,
                    # ma_ho_so
                    None,
                    # ma_nb
                    None,
                    # mac_dinh
                    random.choice([True, False]),
                    # nb_thong_tin_id
                    random.choice(self.dm_benh_nhan_id),
                    # ngay_sinh
                    self.fake.date_of_birth(minimum_age=0, maximum_age=90).strftime(
                        '%Y-%m-%d %H:%M:%S'),
                    # nghe_nghiep_id
                    str(self.fake.random_int(min=1, max=100)),
                    # ngoai_vien
                    random.choice([True, False]),
                    # nguoi_lap_benh_an_id
                    None,
                    # nhom_mau
                    None,
                    # noi_lam_viec
                    self.fake.company(),
                    # phan_loai_nb_id
                    "1",
                    # quoc_tich_id
                    2,
                    # so_bao_hiem_xa_hoi
                    self.fake.ssn(),
                    # so_dien_thoai
                    self.fake.phone_number(),
                    # so_ngay_dieu_tri
                    1,
                    # so_phoi
                    None,
                    # ten_nb
                    self.ten_nb,
                    # ten_nb_khong_dau
                    self.ten_nb_khong_dau,
                    # thoi_gian_lap_benh_an
                    None,
                    # thoi_gian_ra_vien
                    None,
                    # thoi_gian_vao_vien
                    self.thoi_gian_vao_vien,
                    # tiem_chung
                    False,
                    # trang_thai
                    5,
                    # uu_tien
                    False,
                    # duyet_chi_phi
                    None,
                    # bang_lai_xe_id
                    None,
                    # ma_doi_tuong_kcb_id
                    None,
                    # nhan_vien_kinh_doanh_id
                    None,
                    # can_nang_vao_vien
                    None,
                    # cong_ty_bao_hiem_id
                    None,
                    # phan_loai_doi_tuong
                    random.choice([10, 20]),
                    # nguoi_duyet_chi_phi_id
                    None,
                    # nguoi_gui_duyet_chi_phi_id
                    None,
                    # nguoi_tu_choi_duyet_chi_phi_id
                    None,
                    # loai_lien_ket
                    None,
                    # nb_lien_ket_id
                    None,
                    # ho_ngheo
                    False,
                    # active
                    True,
                    # deleted
                    0,
                    # created_at
                    now,
                    # updated_at
                    now
                )
                records.append(record)

            # SQL Insert
            columns = (
                "cap_cuu, chi_nam_sinh, dan_toc_id, doi_tuong, doi_tuong_kcb, email, gioi_tinh, "
                "kham_suc_khoe, khoa_id, khoa_tiep_don_id, loai_benh_an_id, loai_doi_tuong_id, ma_benh_an, "
                "ma_ho_so, ma_nb, mac_dinh, nb_thong_tin_id, ngay_sinh, nghe_nghiep_id, ngoai_vien, "
                "nguoi_lap_benh_an_id, nhom_mau, noi_lam_viec, phan_loai_nb_id, quoc_tich_id, "
                "so_bao_hiem_xa_hoi, so_dien_thoai, so_ngay_dieu_tri, so_phoi, ten_nb, ten_nb_khong_dau, "
                "thoi_gian_lap_benh_an, thoi_gian_ra_vien, thoi_gian_vao_vien, tiem_chung, trang_thai, "
                "uu_tien, duyet_chi_phi, bang_lai_xe_id, ma_doi_tuong_kcb_id, nhan_vien_kinh_doanh_id, "
                "can_nang_vao_vien, cong_ty_bao_hiem_id, phan_loai_doi_tuong, nguoi_duyet_chi_phi_id, "
                "nguoi_gui_duyet_chi_phi_id, nguoi_tu_choi_duyet_chi_phi_id, loai_lien_ket, nb_lien_ket_id, "
                "ho_ngheo, active, deleted, created_at, updated_at"
            )

            # add RETURNING
            query = f"INSERT INTO pgsql_source.ct_dot_dieu_tri ({columns}) VALUES %s RETURNING id"
            # Set page_size to handle all records in one batch to retrieve all IDs via RETURNING
            execute_values(cursor, query, records, page_size=len(records))

            dot_dieu_tri_ids = [r[0] for r in cursor.fetchall()]

            # --- CT_PHIEU_THU ---
            phieu_thu_records = []
            for ddt_id in dot_dieu_tri_ids:
                # Giả lập các measures theo fact_thanh_toan và sample data trong README.md
                thanh_tien_val = float(random.randint(1000000, 20000000))
                # 0% hoặc 80% hoặc 100% bảo hiểm
                tien_bh_val = float(
                    thanh_tien_val * random.choice([0, 0.8, 1.0]))
                tien_giam_gia_val = float(random.randint(0, 50000))
                amount_nb_tu_tra = thanh_tien_val - tien_bh_val - tien_giam_gia_val

                phieu_thu_records.append((
                    True,                   # active
                    0,                      # deleted
                    ddt_id,                 # nb_dot_dieu_tri_id
                    1.0,                    # ca_lam_viec_id
                    1,                      # doi_tuong_kcb
                    random.choice([0.0, 10.0, 20.0]),  # hinh_thuc_mien_giam
                    f"FAKE_{random.randint(100, 999)}",  # ky_hieu
                    0,                      # loai_phieu_thu
                    1.0,                    # nha_thu_ngan_id
                    float(random.randint(1, 5)),  # quay_id
                    random.randint(10000000, 99999999),  # so_phieu
                    thanh_tien_val,         # thanh_tien
                    # thanh_toan (int4, khớp với sample data value 50)
                    50,
                    now.strftime('%Y-%m-%d %H:%M:%S'),  # thoi_gian_thanh_toan
                    429.0,                  # thu_ngan_id (sample data 429.0)
                    tien_bh_val,            # tien_bh_thanh_toan
                    tien_giam_gia_val,      # tien_giam_gia
                    0.0,                    # tien_hoan_tra
                    # tien_nb_tu_tra (Số tiền NB thực trả)
                    amount_nb_tu_tra,
                    # trang_thai_hoa_don (khớp sample data 10)
                    10,
                    False,                  # hoan_ung
                    # thoi_gian_tao_phieu
                    now.strftime('%Y-%m-%d %H:%M:%S.%f'),
                    # thoi_gian_cap_nhat_phieu
                    now.strftime('%Y-%m-%d %H:%M:%S.%f'),
                    now,                    # created_at
                    now                     # updated_at
                ))

            if phieu_thu_records:
                phieu_thu_cols = (
                    "active, deleted, nb_dot_dieu_tri_id, ca_lam_viec_id, doi_tuong_kcb, "
                    "hinh_thuc_mien_giam, ky_hieu, loai_phieu_thu, nha_thu_ngan_id, "
                    "quay_id, so_phieu, thanh_tien, thanh_toan, thoi_gian_thanh_toan, "
                    "thu_ngan_id, tien_bh_thanh_toan, tien_giam_gia, tien_hoan_tra, "
                    "tien_nb_tu_tra, trang_thai_hoa_don, hoan_ung, thoi_gian_tao_phieu, "
                    "thoi_gian_cap_nhat_phieu, created_at, updated_at"
                )
                phieu_thu_query = f"INSERT INTO pgsql_source.ct_phieu_thu ({phieu_thu_cols}) VALUES %s"
                execute_values(cursor, phieu_thu_query, phieu_thu_records)

            conn.commit()
            print(
                f"🚀 Successfully inserted {len(records)} episodes and {len(phieu_thu_records)} receipts.")
        finally:
            cursor.close()
            conn.close()


if __name__ == "__main__":
    faker_gen = FakerGenerator()
    faker_gen.generate_fake_data()
