services:
  dbt:
    image: ${WAREHOUSE_DBT_IMAGE}
    container_name: dbt-warehouse
    entrypoint: ""
    working_dir: /usr/app/dbt
    volumes:
      - ./dbt_project:/usr/app/dbt
      - ./.dbt:/root/.dbt
    env_file:
      - ../../../.env
    ports:
      - "127.0.0.1:8183:8182"
    environment:
      - DBT_PROFILES_DIR=/root/.dbt
    command: >
      /bin/sh -c "dbt deps && dbt docs generate && dbt docs serve --port 8182 --host 0.0.0.0"
    networks:
      - warehouse-net

networks:
  warehouse-net:
    external: true
