services:
  dbt:
    image: ${WAREHOUSE_DBT_IMAGE}
    container_name: dbt-warehouse
    volumes:
      - ../../../src/dbt_project:/usr/app/dbt
      - ./.dbt:/root/.dbt
    env_file:
      - ../../../.env
    command: ["debug"]
    networks:
      - warehouse-net

networks:
  warehouse-net:
    external: true
