spark.eventLog.enabled           true
spark.eventLog.dir               file:///tmp/spark-events
spark.history.fs.logDirectory    file:///tmp/spark-events
spark.sql.shuffle.partitions     200
spark.driver.host                spark-master
spark.driver.bindAddress         0.0.0.0

spark.executor.memory        4g
spark.executor.cores         2
spark.cores.max              2
spark.executor.memoryOverhead 512m
spark.driver.memory              512m
spark.executor.extraJavaOptions  -XX:+UseContainerSupport -XX:MaxDirectMemorySize=2g
spark.sql.files.maxPartitionBytes    134217728
spark.sql.files.openCostInBytes      134217728