name: hospital_dwh_dbt
version: 1.0.0
config-version: 2

profile: hospital_dwh_dbt

dispatch:
  - macro_namespace: automate_dv
    search_order: ['hospital_dwh_dbt', 'automate_dv']

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  hospital_dwh_dbt:
    staging:
      +schema: staging
      +materialized: view
    raw_vault:
      +schema: raw_vault
      +materialized: incremental
    reference:
      +schema: reference
      +materialized: table
    business_vault:
      +schema: business_vault
      +materialized: incremental
