# Flink Iceberg Catalog Configuration
catalog.name=hospital_catalog
type=iceberg
catalog.type=hive
catalog.warehouse=s3a://hospital-datalake/
#catalog.uri=http://172.30.2.234:9083/
catalog.uri=thrift://hive-metastore:9083


# Kafka Source Configuration
#kafka.bootstrap.servers=localhost:9092
kafka.bootstrap.servers=kafka:9094
#kafka.bootstrap.servers=172.30.2.234:9092
kafka.scan.startup.mode=latest-offset
kafka.topic.prefix=hospital.pgsql_source.

# Sink Configuration
sink.database.name=hospital_db_sink

# S3/MinIO Configuration
#s3.endpoint=http://172.30.2.234:9000
s3.endpoint=http://minio:9000
s3.access-key-id=admin
s3.secret-access-key=741852963
s3.region=us-east-1

# Flink Checkpointing Configuration
flink.checkpoints.dir=s3://flink-checkpoints/checkpoints
flink.savepoints.dir=s3://flink-savepoints/savepoints
######################### Batch Job Specific Configurations #########################
# Batch job check pointing directory
batch.minio.checkpoints.dir=s3a://batch-checkpoints/
#batch.kafka.topic.prefix=hospital.checkpoints
batch.step=1000
##########################  Partition Group Size  ##########################
partition.division.size=100