services:
  spark-master:
    build:
      context: ..
      dockerfile: spark/Dockerfile
    image: ${WAREHOUSE_SPARK_IMAGE}
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "127.0.0.1:${WAREHOUSE_SPARK_MASTER_PORT}:7077"
      - "127.0.0.1:${WAREHOUSE_SPARK_WEBUI_PORT}:8085"
    env_file:
      - ../../../.env
    environment:
      - SPARK_ENV=docker
      - SPARK_MASTER_OPTS=-Xmx512m
    volumes:
      - ./conf/spark-env.sh:/opt/spark/conf/spark-env.sh
      - ./conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./spark_jobs:/opt/spark/spark_jobs
      - ../jars:/opt/spark/user_jars
    mem_limit: 1g
    memswap_limit: 1g
    networks:
      - lake-net
      - warehouse-net
      - elastic-net

  spark-worker:
    image: ${WAREHOUSE_SPARK_IMAGE}
    # container_name: spark-worker  <-- Comment out để Docker Compose tự sinh tên
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "127.0.0.1::8081" # <-- Bỏ map port cố định để không bị đụng port khi scale 2 node
    env_file:
      - ../../../.env
    mem_limit: 4g
    memswap_limit: 4g
    environment:
      - SPARK_ENV=docker
      - SPARK_WORKER_MEMORY=3g      # Spark dùng để cấp cho executor
      - SPARK_WORKER_OPTS=-Xmx512m
    volumes:
      - ./conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./conf/hive-site.xml:/opt/spark/conf/hive-site.xml
      - ./spark_jobs:/opt/spark/spark_jobs
      - ../jars:/opt/spark/user_jars

    networks:
      - lake-net
      - warehouse-net
      - elastic-net

networks:
  lake-net:
    external: true
  warehouse-net:
    external: true
  elastic-net:
    external: true
