version: '3.8'

services:
  # =========================================
  # Kafka Cluster (KRaft Mode - No ZooKeeper)
  # =========================================
  kafka:
    image: ${SOURCE_KAFKA_IMAGE}
    container_name: kafka
    restart: always
    hostname: kafka
    env_file:
      - ../../../.env
    ports:
      - "${SOURCE_KAFKA_PORT_EXT}:9092" # External access
    environment:
      # KRaft Settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      
      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:${SOURCE_KAFKA_PORT_EXT},INTERNAL://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Cluster ID for KRaft mode
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"



    volumes:
      - ./data:/var/lib/kafka/data
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - source_net

  # =========================================
  # Kafka UI (Provectus)
  # =========================================
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - ../../../.env
    ports:
      - "${SOURCE_KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: hospital-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - source_net

networks:
  source_net:
    external: true
