version: '3.8'

services:
  # =========================================
  # 2. Kafka Cluster (KRaft Mode - No ZooKeeper)
  # =========================================
  kafka:
    image: ${SOURCE_KAFKA_IMAGE}
    container_name: kafka
    restart: always
    hostname: kafka
    env_file:
      - ../../../.env
    ports:
      - "${SOURCE_KAFKA_PORT_EXT}:9092" # External access
    environment:
      # KRaft Settings
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_KRAFT_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      
      # Listeners
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:${SOURCE_KAFKA_PORT_EXT},INTERNAL://kafka:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - ./data:/bitnami/kafka
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - hospital_network

networks:
  hospital_network:
    external: true
